<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Judhur.Application\Judhur.Application.csproj" />
    <ProjectReference Include="..\Judhur.Contracts\Judhur.Contracts.csproj" />
    <ProjectReference Include="..\Judhur.Infrastructure\Judhur.Infrastructure.csproj" />
  </ItemGroup>

</Project>
